name: Update README to show seeds-random

on:
  workflow_dispatch:  # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Update README to show seeds-random
      run: |
        sed -i 's|<img src="./seeds-exploding.svg"|<img src="./seeds-random.svg"|g' README.md
        sed -i 's|<img src="./seeds-random.svg"|<img src="./seeds-random.svg"|g' README.md
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "🌱 Update README to show random seeds demo"
        git push
