name: Update README to show langtons-ant

on:
  workflow_dispatch:  # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Update README to show langtons-ant
      run: |
        sed -i 's|<img src="./langtons-random.svg" alt="Langton'"'"'s Ant"/>|<img src="./langtons-ant.svg" alt="Langton'"'"'s Ant"/>|g' README.md
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "🐜 Update README to show Langton's ant demo"
        git push
